### ISSUE TITLE
Fix Toolbar on Samsung devices

### ISSUE THREAD

**Issue by adamsp** [adamsp/DestinyRaidTimers#5]
[Come on Samsung](https://code.google.com/p/android/issues/detail?id=78377).

```
java.lang.NoClassDefFoundError: android.support.v7.internal.view.menu.MenuBuilder
       at android.support.v7.widget.ActionMenuView.getMenu(ActionMenuView.java:620)
       at android.support.v7.widget.Toolbar.ensureMenu(Toolbar.java:825)
       at android.support.v7.widget.Toolbar.getMenu(Toolbar.java:817)
       at android.support.v7.internal.app.ToolbarActionBar.getMenu(ToolbarActionBar.java:554)
       at android.support.v7.internal.app.ToolbarActionBar.setListMenuPresenter(ToolbarActionBar.java:558)
       at android.support.v7.app.ActionBarActivityDelegateBase.setSupportActionBar(ActionBarActivityDelegateBase.java:178)
       at android.support.v7.app.ActionBarActivity.setSupportActionBar(ActionBarActivity.java:92)
       at nz.net.speakman.destinyraidtimers.crota.CrotaFragment.onCreateView(CrotaFragment.java:99)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:1786)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:947)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:739)
       at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1489)
       at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:548)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1181)
       at android.app.Activity.performStart(Activity.java:5336)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2222)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2304)
       at android.app.ActivityThread.access$700(ActivityThread.java:152)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1284)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:176)
       at android.app.ActivityThread.main(ActivityThread.java:5299)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:511)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

**Comment by adamsp** [comment]
Looks like [comment 138](https://code.google.com/p/android/issues/detail?id=78377#c138) might be the way to go to fix this.

**Comment by adamsp** [comment]
Actually, [this StackOverflow answer](http://stackoverflow.com/a/27644579/1217087) might be better:

```
-keep class !android.support.v7.internal.view.menu.MenuBuilder, !android.support.v7.internal.view.menu.SubMenuBuilder, android.support.v7.** { *; }
-keep interface android.support.v7.** { *; }
```

**Comment by adamsp** [comment]
http://www.crashlytics.com/blog/mastering-proguard-for-building-lightweight-android-code/

**Comment by adamsp** [comment]
Delayed again. Turns out that Dagger _really_ doesn't play well with Proguard. Need to move to Dagger 2 (and probably ButterKnife 6) in order to fix this.

**Comment by adamsp** [comment]
https://support.google.com/googleplay/android-developer/answer/1286017?hl=en# Just outright excluding the failing devices for now, so those users can't install the app.
