### ISSUE TITLE
eglCreateContext failed with error: EGL_BAD_ALLOC

### ISSUE THREAD

**Issue by adamsp** [adamsp/DestinyRaidTimers#6]
Nexus 4 running 4.4.2

java.lang.IllegalStateException: Could not create an EGL context. eglCreateContext failed with error: EGL_BAD_ALLOC
       at android.view.HardwareRenderer$GlRenderer.createContext(HardwareRenderer.java:1278)
       at android.view.HardwareRenderer$GlRenderer.initializeEgl(HardwareRenderer.java:1126)
       at android.view.HardwareRenderer$GlRenderer.initialize(HardwareRenderer.java:1057)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1550)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1000)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5670)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:761)
       at android.view.Choreographer.doCallbacks(Choreographer.java:574)
       at android.view.Choreographer.doFrame(Choreographer.java:544)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:747)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5017)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
       at dalvik.system.NativeStart.main(NativeStart.java)
http://crashes.to/s/aed47901e5c

**Comment by adamsp** [comment]
This [_appears_](https://code.google.com/p/android/issues/detail?id=61868) to be an issue with the Nexus 4, rather than specific to this app.

**Comment by adamsp** [comment]
See also: http://stackoverflow.com/q/19748856
